web/router.ex
defmodule Rumbl.Router do
  use Rumbl.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Rumbl.Auth, repo: Rumbl.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Rumbl do
    pipe_through :browser
    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/watch/:id", WatchController, :show
  end

  scope "/manage", Rumbl do
    pipe_through [:browser, :authenticate_user]
    resources "/videos", VideoController
    resources "/categories", CategoryController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Rumbl do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Rumbl.LayoutView do
  use Rumbl.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Rumbl!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Rumbl</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <%= if @current_user do %>
            <ul class="nav navbar-nav">
              <li><%= link "My Videos", to: video_path(@conn, :index) %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @current_user.username %>&nbsp;<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link String.capitalize(@current_user.username), to: user_path(@conn, :show, @current_user.id) %></li>
                  <li>
                    <%= link "Log Out", to: session_path(@conn, :delete, @current_user), method: "delete", class: "form-control" %>
                  </li>
                </ul>
              </li>
            </ul>
          <% else %>
            <%= form_for @conn, session_path(@conn, :create), [as: :session, class: "navbar-form navbar-right"], fn f -> %>
              <div class="form-group">
                <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
              </div>
              <div class="form-group">
                <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
              </div>
              <%= submit "Login", class: "btn btn-primary" %>
              <%= link "Register", to: user_path(@conn, :new), class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-12">
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        </div>
        <div class="col-md-12">
          <main role="main">
            <%= render @view_module, @view_template, assigns %>
          </main></div>
      </div>
    </div> <!-- /container -->
    <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy; 2015 Rumbl, Inc.</p>
      </div>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>